# Generated by Django 4.2.2 on 2023-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Неизвестный', max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=2000, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Гостевая книга',
                'verbose_name_plural': 'Гостевые книги',
                'db_table': 'Book',
            },
        ),
    ]
